[package]
name = "lrgex_restore"
version = "1.6.2"
edition = "2021"

[[bin]]
name = "LRGEXRestore"
path = "src/main.rs"

[dependencies]
slint = { version = "1.17", features = ["backend-winit", "renderer-software"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
winreg = "0.55"
windows-sys = { version = "0.59", features = ["Win32_System_Threading", "Win32_Foundation", "Win32_UI_Shell", "Win32_System_Com", "Win32_System_Console", "Win32_Storage_FileSystem", "Win32_Security"] }
chrono = "0.4"
rfd = "0.15"
ureq = { version = "2", features = ["json"] }
tar = "0.4"
zstd = { version = "0.13", features = ["zstdmt"] }
sha2 = "0.10"
hex = "0.4"
ed25519-dalek = "2"
rand = "0.8"
rayon = "1"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true


[build-dependencies]
winres = "0.1"

[[bin]]
name = "keygen"
path = "src/keygen.rs"

[[bin]]
name = "sign"
path = "src/sign.rs"
